version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: