name: OWASP ZAP API Scan

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start OWASP ZAP
      run: docker run -d --name zap -u zap -p 8080:8080 -i owasp/zap2docker-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true

    - name: Wait for ZAP to start
      run: |
        for i in {1..30}; do
          if docker logs zap | grep 'ZAP is now listening'; then
            break
          fi
          sleep 2
        done

    - name: Run ZAP API Scan
      run: docker exec zap zap-api-scan.py -t <API-URL> -f openapi -r zap_report.html
      env:
        API-URL: "http://localhost:8080/FileHandler" # Add your API URL in the repository secrets

    - name: Copy ZAP Report
      run: docker cp zap:/zap/zap_report.html .
    
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: zap_report.html

    - name: Stop OWASP ZAP
      run: docker stop zap
