name: OWASP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    zap_scan:
      runs-on: self-hosted
      name: Scan the webapplication
      steps:
        - name: ZAP Scan
          uses: zaproxy/action-api-scan@v0.7.0
          with:
            target: 'http://localhost:8080/FileHandler'
