name: OWASP ZAP Integration with GitHub Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:latest'
          target: 'http://localhost:5000/api/FileHandler'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
